global using System;
global using System.Collections.Generic;
global using System.Drawing;
global using System.Linq;
global using System.Windows.Forms;
global using BBQ.Toolkit.Common;
global using BBQ.Toolkit.Properties;
global using Extenso.Collections;
global using Krypton.Toolkit;